version: "3.8"

services:
  nginx:
    container_name: proxy
    build: europe-west6-docker.pkg.dev/ardunio-api/docker-repo/api_frontend
    restart: always
    ports: 
      - 443:443
      - 80:80

  redis_server:
    container_name: redisserver
    image: redis
    hostname: redisserver
    restart: always
    ports:
      - 6379:6379

  api:  
    container_name: api
    depends_on:
      - redis_server
      - nginx_proxy
    image: europe-west6-docker.pkg.dev/ardunio-api/docker-repo/api_backend
    restart: always
    ports:
      - 80:3300
      - 8090:3000

